Repository USACE/groundwork, pull requests merged in 2024-08, with the labels that each got.

#97 Compliance/508 corrections from IT Scan
  lib/catalyst/avatar.jsx
  lib/components/hero.jsx
  lib/components/layout/usace-box.jsx
  lib/components/profile-dropdown.jsx
  lib/components/table.jsx
  lib/composite/footer/essayons.jsx
  lib/composite/footer/logo-banner.jsx
  lib/composite/header/index.jsx
  lib/composite/header/usa-banner/USABanner.jsx
  lib/composite/header/usa-banner/usa-banner.css
  tailwind.config.js
Labels: accessibility, minor-bump

#98 update readme
  README.md
Labels: patch-bump

#93 Remove WM components
  lib/components/water-management/CdaLatestValueCard.jsx
  lib/components/water-management/cda.js
  lib/components/water-management/nwps.ts
  lib/components/water-management/useCdaCatalogTS.js
  lib/components/water-management/useCdaLatestValue.js
  lib/components/water-management/useCdaLocation.js
  lib/components/water-management/useCdaTimeSeries.js
  lib/components/water-management/useCdaTimeSeriesGroup.js
  lib/components/water-management/useNwpsGauge.js
  lib/components/water-management/useNwpsGaugeData.js
  lib/index.jsx
  package-lock.json
  package.json
  src/app-bundles/route-bundle.js
  src/app-components/water-management/cda-params-table.jsx
  src/app-components/water-management/query-client-warning.jsx
  src/app-components/water-management/shared-docs.jsx
  src/app-pages/documentation/water-management/cda-latest-value-card.jsx
  src/app-pages/documentation/water-management/data-hooks.jsx
  src/app-pages/documentation/water-management/index.jsx
  src/app-pages/documentation/water-management/use-cda-catalog-ts.jsx
  src/app-pages/documentation/water-management/use-cda-latest-value.jsx
  src/app-pages/documentation/water-management/use-cda-location.jsx
  src/app-pages/documentation/water-management/use-cda-time-series-group.jsx
  src/app-pages/documentation/water-management/use-cda-time-series.jsx
  src/app-pages/documentation/water-management/use-nwps-gauge-data.jsx
  src/app-pages/documentation/water-management/use-nwps-gauge.jsx
  src/main.jsx
  src/nav-links.js
  vite.config.js
Labels: major-bump

#100 Remove static size to prevent long text overlapping
  lib/components/layout/usace-box.jsx
Labels: patch-bump
