Repository USACE/groundwork, pull requests merged in 2024-05, with the labels that each got.

#49 NWPS Hooks
  lib/components/water-management/nwps.ts
  lib/components/water-management/useNwpsGauge.js
  lib/components/water-management/useNwpsGaugeData.js
  lib/index.jsx
  src/app-bundles/route-bundle.js
  src/app-components/water-management/cda-params-table.jsx
  src/app-components/water-management/shared-docs.jsx
  src/app-pages/documentation/water-management/use-nwps-gauge-data.jsx
  src/app-pages/documentation/water-management/use-nwps-gauge.jsx
  src/nav-links.js
Labels: enhancement

#58 2.5.2
  package-lock.json
  package.json
Labels: versioning

#60 useCdaLatestValue Hook
  lib/components/water-management/CdaLatestValueCard.jsx
  lib/components/water-management/useCdaLatestValue.js
  lib/index.jsx
  src/app-bundles/route-bundle.js
  src/app-components/water-management/cda-params-table.jsx
  src/app-components/water-management/shared-docs.jsx
  src/app-pages/documentation/water-management/use-cda-latest-value.jsx
  src/nav-links.js
Labels: enhancement

#62 Added missing quotes for breadcrumbs
  src/app-pages/documentation/navigation/breadcrumbs.jsx
Labels: bug, documentation

#67 37 docs internal links break when opened in new tab
  src/App.jsx
  src/app-components/water-management/query-client-warning.jsx
  src/app-pages/404.jsx
  src/app-pages/documentation/_template.jsx
  src/app-pages/documentation/app-shell/index.jsx
  src/app-pages/documentation/app-shell/search.jsx
  src/app-pages/documentation/app-shell/site-wrapper.jsx
  src/app-pages/documentation/buttons/delete-confirm.jsx
  src/app-pages/documentation/buttons/generic-buttons.jsx
  src/app-pages/documentation/buttons/index.jsx
  src/app-pages/documentation/buttons/login-button.jsx
  src/app-pages/documentation/buttons/ok-cancel.jsx
  src/app-pages/documentation/display/accordion.jsx
  src/app-pages/documentation/display/badge.jsx
  src/app-pages/documentation/display/card.jsx
  src/app-pages/documentation/display/headings.jsx
  src/app-pages/documentation/display/hero.jsx
  src/app-pages/documentation/display/index.jsx
  src/app-pages/documentation/display/skeleton.jsx
  src/app-pages/documentation/display/table.jsx
  src/app-pages/documentation/display/text.jsx
  src/app-pages/documentation/forms/color-input.jsx
  src/app-pages/documentation/forms/date-time-inputs.jsx
  src/app-pages/documentation/forms/fieldset.jsx
  src/app-pages/documentation/forms/file-input.jsx
  src/app-pages/documentation/forms/index.jsx
  src/app-pages/documentation/forms/input.jsx
  src/app-pages/documentation/forms/numeric-inputs.jsx
  src/app-pages/documentation/forms/text-input.jsx
  src/app-pages/documentation/forms/textarea.jsx
  src/app-pages/documentation/getting-started/adding-tailwind.jsx
  src/app-pages/documentation/getting-started/client-side-routing.jsx
  src/app-pages/documentation/getting-started/quick-start-guide.jsx
  src/app-pages/documentation/index.jsx
  src/app-pages/documentation/layout/container.jsx
  src/app-pages/documentation/layout/index.jsx
  src/app-pages/documentation/layout/usace-box.jsx
  src/app-pages/documentation/navigation/breadcrumbs.jsx
  src/app-pages/documentation/navigation/index.jsx
  src/app-pages/documentation/navigation/tabs.jsx
  src/app-pages/documentation/plots/heatmap.jsx
  src/app-pages/documentation/plots/index.jsx
  src/app-pages/documentation/plots/plotly-wrapper.jsx
  src/app-pages/documentation/types/index.jsx
  src/app-pages/documentation/types/link.jsx
  src/app-pages/documentation/types/tab.jsx
  src/app-pages/documentation/water-management/cda-latest-value-card.jsx
  src/app-pages/documentation/water-management/data-hooks.jsx
  src/app-pages/documentation/water-management/index.jsx
  src/app-pages/documentation/water-management/use-cda-catalog-ts.jsx
  src/app-pages/documentation/water-management/use-cda-latest-value.jsx
  src/app-pages/documentation/water-management/use-cda-location.jsx
  src/app-pages/documentation/water-management/use-cda-time-series-group.jsx
  src/app-pages/documentation/water-management/use-cda-time-series.jsx
  src/app-pages/documentation/water-management/use-nwps-gauge-data.jsx
  src/app-pages/documentation/water-management/use-nwps-gauge.jsx
  src/app-pages/home.jsx
  src/nav-links.js
Labels: patch-bump
